# Generated by Django 3.0.7 on 2020-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techused',
            name='tech_name',
            field=models.CharField(max_length=100),
        ),
    ]
