# Generated by Django 3.0.7 on 2020-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0002_auto_20200708_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
